fixtures:

  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    nodejs: "https://github.com/willdurand/puppet-nodejs.git"
    mongodb: "https://github.com/puppetlabs/puppetlabs-mongodb"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
