fixtures:

  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    nodejs: 'https://github.com/voxpupuli/puppet-nodejs'
    mongodb: "https://github.com/puppetlabs/puppetlabs-mongodb"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    wget: 'https://github.com/maestrodev/puppet-wget.git'
    archive: 'https://github.com/voxpupuli/puppet-archive.git'
