language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
  - wget_cache
rvm:
  - 2.2.5
  - 2.3.1
before_install:
  -  gem update --system 2.1.11
script:
  - bundle exec rake validate
  - bundle exec rake spec
  - bundle exec rake beaker
notifications:
  email:
    - cosaquee@gmail.com
env:
  - PUPPET_VERSION=4.2.3
  - PUPPET_VERSION=4.3.2
  - PUPPET_VERSION=4.4.2
  - PUPPET_VERSION=4.6.2
  - PUPPET_VERSION=4.8.1
  - PUPPET_VERSION=4.9.0

matrix:
  exclude:
    - rvm: 2.2.5
      env: PUPPET_VERSION=3.8.7
    - rvm: 2.3.1
      env: PUPPET_VERSION=3.8.7
    - rvm: 2.0.0
      env: PUPPET_VERSION=4.9.0
