language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
  - wget_cache
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
before_install:
  -  gem update --system 2.7.7
script:
  - bundle exec rake validate
  - bundle exec rake spec
notifications:
  email:
    - cosaquee@gmail.com
env:
  - PUPPET_VERSION=4.3.2 FIXTURES_YML=.fixtures-43.yml
  - PUPPET_VERSION=4.4.2 FIXTURES_YML=.fixtures-43.yml
  - PUPPET_VERSION=4.6.2
  - PUPPET_VERSION=4.8.2
  - PUPPET_VERSION=4.9.4
  - PUPPET_VERSION=4.10.11
  - PUPPET_VERSION=5.5.1
matrix:
  exclude:
    - rvm: 2.2.10
      env: PUPPET_VERSION=5.5.1
